datapanel/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

urlpatterns = patterns('',
                       url(r'^$', 'datapanel.views.index', name='index'),
                       url(r'^track_pool/$',
                           'datapanel.views.track_pool', name='track_pool'),
                       url(r'^server_info/$',
                           'datapanel.views.server_info', name='server_info'),
                       url(r'^a/$', 'datapanel.views.a'),

                       (r'^accounts/', include(
                           'registration.backends.default.urls')),
                       (r'^project/', include('project.urls')),
                       (r'^funnel/', include('funnel.urls')),
                       (r'^track/', include('track.urls')),
                       (r'^session/', include('session.urls')),
                       (r'^ecshop/', include('ecshop.urls')),
                       (r'^referrer/', include('referrer.urls')),
                       )

urlpatterns += patterns('django.views.generic.simple',
                        (r'^js/(?P<key>\w+)/$', cache_page(60 * 60 * 24)(TemplateView.as_view(
                                                                         template_name='js_template.js', content_type='application/x-javascript')),
                         )
                        )

project/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
   url(r'^create/$', 'project.views.create', name='project_create'),
   url(r'^(?P<id>\d+)/$', 'project.views.home', name='project_home'),
   url(r'^(?P<id>\d+)/overview/$', 'project.views.overview', name='project_overview'),
   url(r'^(?P<id>\d+)/monitor/$', 'project.views.monitor', name='project_monitor'),
   url(r'^(?P<id>\d+)/delete/$', 'project.views.delete', name='project_delete'),
   url(r'^(?P<id>\d+)/setting/$', 'project.views.setting', name='project_setting'),


   url(r'^(?P<id>\d+)/action/$', 'project.views.action.list', name='action_list'),
   url(r'^(?P<id>\d+)/action/create/$', 'project.views.action.create', name='action_create'),
   url(r'^(?P<id>\d+)/action/(?P<aid>\d+)/update/$', 'project.views.action.update', name='action_update'),
   url(r'^(?P<id>\d+)/action/(?P<aid>\d+)/delete/$', 'project.views.action.delete', name='action_delete'),

)

registration/urls.py
"""
Backwards-compatible URLconf for existing django-registration
installs; this allows the standard ``include('registration.urls')`` to
continue working, but that usage is deprecated and will be removed for
django-registration 1.0. For new installs, use
``include('registration.backends.default.urls')``.

"""

import warnings

warnings.warn("include('registration.urls') is deprecated; use include('registration.backends.default.urls') instead.",
              PendingDeprecationWarning)

from registration.backends.default.urls import *

track/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       # url(r'^(?P<id>\d+)/groupby_value/$', 'track.views.groupby.value', name='track_groupby_value'),
                       url(r'^(?P<id>\d+)/groupby_action/$', 'track.views.groupby.action', name='track_groupby_action'),
                       url(r'^(?P<id>\d+)/get_url_by_value/$', 'track.views.get_url_by_value', name='track_get_url_by_value'),
                       url(r'^(?P<id>\d+)/get_referrer_url/$', 'track.views.get_referrer_url', name='track_get_referrer_url'),
                       )

project/models.py
#coding=utf-8
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    """docstring for Project"""
    name = models.CharField(max_length=20, verbose_name=u'项目名称')
    url = models.CharField(max_length=255, verbose_name=u'项目URL')
    dateline = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True)
    lastview = models.DateTimeField(verbose_name=u'最后访问时间', auto_now=True)
    creator = models.ForeignKey(User, verbose_name=u'创建用户', related_name='create_project')
    participants = models.ManyToManyField(User, verbose_name=u'参与用户', related_name='participate_projects')
    key = models.CharField(max_length=255, verbose_name=u'', default='')
    token = models.CharField(max_length=255, verbose_name=u'', default='')

    class Meta:
        unique_together = (('name', 'creator'),)
        ordering = ['-lastview']

    def __unicode__(self):
        return self.name

    def add_action(self, name, url):
        a = Action.objects.get_or_create(project=self, name=name)
        if a[1]:
            a[0].url = url
            a[0].save()
        return a[0]


class Action(models.Model):
    """
    Websites' managers defined their own actions
    """
    IS_FLAG_CHOICES = (('Y', '是'), ('N', '否'))
    project = models.ForeignKey(Project, related_name='action')
    name = models.CharField(max_length=255, verbose_name=u'行为名称')
    url = models.CharField(max_length=255, verbose_name=u'URL正则', null=True, blank=True)
    xpath = models.CharField(max_length=255, verbose_name=u'控件', null=True, blank=True)
    event = models.CharField(max_length=255, verbose_name=u'事件', null=True, blank=True)
    is_flag = models.CharField(max_length=1, verbose_name=u'是否是成功标识', null=False, blank=False, default='N', choices=IS_FLAG_CHOICES)

    def __unicode__(self):
        return self.name

    class Meta:
        unique_together = (('name', 'project'),)


class Keyword(models.Model):
    """
    Websites' manager focus their keyword
    """
    project = models.ForeignKey(Project, related_name='keywords')
    name = models.CharField(max_length=20, verbose_name='关键词')

    class Meta:
        unique_together = (('project', 'name'))

project/forms.py
#coding=utf-8
from bootstrap.forms import BootstrapModelForm, Fieldset
from project.models import Project, Action


class ProjectForm(BootstrapModelForm):
    class Meta:
        layout = (
            Fieldset(u"设置", "name", "url", ),
        )
        model = Project
        exclude = ('dateline', 'lastview', 'creator', 'participants', 'key', 'token')


class ActionForm(BootstrapModelForm):
    class Meta:
        layout = (
            Fieldset(u"行为设置", "name", "url", "xpath", "event", "is_flag"),
        )
        model = Action
        exclude = ('project')

datapanel/views/project.py
#coding=utf-8
from django.db.models import Count
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from datapanel.forms import ProjectForm
from datapanel.models import Session, SessionGroupByTime

def create(request):
    form = ProjectForm()
    if request.method=="POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.creator = request.user
            project.save()
            import time, md5
            #project.token = md5.new(str(project.id + time.mktime(project.dateline.timetuple()))).hexdigest()
            project.token = md5.new(str(project.id + 54321)).hexdigest()
            project.participants.add(request.user)
            project.save()
            return HttpResponseRedirect(reverse('project_home', args=[project.id]))
    return render(request, 'datapanel/project/create.html', {'form': form})

def home(request, id):
    project = request.user.participate_projects.get(id = id)
    project.save()
    datetype = request.GET.get('datetype','hourline')
    sbt = SessionGroupByTime.objects.filter(project= project,datetype=datetype)
    return render(request, 'datapanel/project/index.html', {'project' : project,'sbt': sbt})

def setting(request, id):
    project = request.user.participate_projects.get(id = id)
    return render(request, 'datapanel/project/setting.html', {'project':project})

def delete(request, id):
    project_name = request.POST.get('project_name', None)
    project = request.user.participate_projects.get(id = id, name=project_name)
    project.delete()
    return HttpResponseRedirect(reverse('index'))

project/views/action.py
#coding=utf-8
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from project.forms import ActionForm
from project.models import Action


def create(request, id):
    project = request.user.participate_projects.get(id=id)
    form = ActionForm()
    if request.method == "POST":
        form = ActionForm(request.POST)
        if form.is_valid():
            action = form.save(commit=False)
            action.project = project
            action.save()
            return HttpResponseRedirect(reverse('action_list', args=[id]))
    return render(request, 'project/action/create.html', {'project': project, 'form': form})


def update(request, id, aid):
    project = request.user.participate_projects.get(id=id)
    action = get_object_or_404(Action, pk=aid)
    form = ActionForm(instance=action)
    if request.method == 'POST':
        form = ActionForm(request.POST, instance=action)
        if form.is_valid():
            action = form.save()
            return HttpResponseRedirect(reverse('action_list', args=[action.project.id]))
    return render(request, 'project/action/update.html', {'project': project, 'form': form})


def delete(request, id, aid):
    action = get_object_or_404(Action, project_id=id, id=aid)
    action.delete()
    return HttpResponseRedirect(reverse('action_list', args=[id]))


def list(request, id):
    project = request.user.participate_projects.get(id=id)
    project_actions = Action.objects.filter(project_id=id)
    paginator = Paginator(project_actions, 25)
    page = request.GET.get('page')
    try:
        action_list = paginator.page(page)
    except PageNotAnInteger:
        action_list = paginator.page(1)
    except EmptyPage:
        action_list = paginator.page(paginator.num_pages)
    page_range = range(100)
    return render(request, 'project/action/list.html', {'project': project, 'action_list': action_list, 'page_range': page_range})

project/templates/project/action/create.html
{%extends 'datapanel/datapanel_base.html'%}
{% block subnav-action %}
    <li class="active">
        <a href="{%url 'action_list' project.id%}">行为设置</a>
    </li>
{% endblock subnav-action %}
{% block content %}
<div class="well span10">
	<form action="" method="post" class="form-horizontal">
		{%csrf_token%}
    	{{ form }}
		<div class="form-actions">
			<button type="submit" class="btn btn-primary">新 建</button>
			<button type="submit" class="btn">取 消</button>
		</div>
	</form>
</div>
{% endblock content %}

project/templates/project/action/list.html
{%extends 'datapanel/datapanel_base.html'%}
{% block subnav-action %}
    <li class="active">
        <a href="{%url 'action_list' project.id%}">行为设置</a>
    </li>
{% endblock subnav-action %}
{% block content %}
    <div class="span10">
        <div class="page-header">
            <a class="btn pull-right" href="{%url 'action_create' project.id%}">添加行为</a>
            <h1>{{project.name}} / action</h1>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th class="action">行为名称</th>
                <th>URL正则</th>
                <th>成功标识</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for action in action_list %}
                <tr>
                    <td class="action">{{action.name}}</td>
                    <td>{{action.url}}</td>
                    <td>{{action.get_is_flag_display}}</td>
                    <td><a href="{%url 'action_update' action.project.id action.id%}">编辑</a>|<a href="{%url 'action_delete' action.project.id action.id%}">删除</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination pagination-right">
            <ul>
                {% if action_list.has_previous %}
                    <li>
                        <a href="?page={{ action_list.previous_page_number }}">上一页</a>
                    </li>
                {% else %}
                    <li class="disabled"><a>上一页</a></li>
                {% endif %}
                {% if action_list.has_next %}
                    <li>
                        <a href="?page={{ action_list.next_page_number }}">下一页</a>
                    </li>
                {% else %}
                    <li class="disabled"><a>下一页</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock content %}

project/templates/project/action/update.html
{%extends 'datapanel/datapanel_base.html'%}

{% block subnav-action %}
    <li class="active">
        <a href="{%url 'action_list' project.id%}">行为设置</a>
    </li>
{% endblock subnav-action %}
{% block content %}
<div class="well span10">
	<form action="" method="post" class="form-horizontal">
		{%csrf_token%}
    	{{ form }}
		<div class="form-actions">
			<button type="submit" class="btn btn-primary">修 改</button>
			<button type="submit" class="btn">取 消</button>
		</div>
	</form>
</div>
{% endblock content %}